package main

import (
	"bufio"
	"context"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"gopkg.in/yaml.v3"

	"github.com/daewoochen/agent-team-go/pkg/channels"
	"github.com/daewoochen/agent-team-go/pkg/observe"
	"github.com/daewoochen/agent-team-go/pkg/runtime"
	"github.com/daewoochen/agent-team-go/pkg/skills"
	"github.com/daewoochen/agent-team-go/pkg/spec"
)

func main() {
	if len(os.Args) < 2 {
		usage()
		os.Exit(1)
	}

	switch os.Args[1] {
	case "init":
		if err := runInit(os.Args[2:]); err != nil {
			exitErr(err)
		}
	case "run":
		if err := runTeam(os.Args[2:]); err != nil {
			exitErr(err)
		}
	case "skills":
		if err := runSkills(os.Args[2:]); err != nil {
			exitErr(err)
		}
	case "channels":
		if err := runChannels(os.Args[2:]); err != nil {
			exitErr(err)
		}
	case "models":
		if err := runModels(os.Args[2:]); err != nil {
			exitErr(err)
		}
	case "replay":
		if err := runReplay(os.Args[2:]); err != nil {
			exitErr(err)
		}
	case "inspect":
		if err := runInspect(os.Args[2:]); err != nil {
			exitErr(err)
		}
	case "version":
		fmt.Println("agentteam v0.1.0")
	default:
		usage()
		os.Exit(1)
	}
}

func usage() {
	fmt.Fprintln(os.Stderr, `agentteam builds and runs multi-agent teams in Go.

Usage:
  agentteam init --name demo --dir ./demo
  agentteam run --team ./team.yaml --task "Ship the v0.1 release"
  agentteam skills install --name github --source local --path ./skills/github
  agentteam skills scaffold --name writing --dir ./skills/writing
  agentteam skills search --query telegram
  agentteam skills list --workdir .
  agentteam channels validate --team ./team.yaml
  agentteam models explain --team ./team.yaml
  agentteam models validate --team ./team.yaml
  agentteam replay show --run ./.agentteam/runs/<run>.json
  agentteam inspect team --team ./team.yaml --format text
  agentteam version`)
}

func runInit(args []string) error {
	fs := flag.NewFlagSet("init", flag.ContinueOnError)
	name := fs.String("name", "demo-team", "team name")
	dir := fs.String("dir", ".", "target directory")
	if err := fs.Parse(args); err != nil {
		return err
	}

	targetDir := filepath.Clean(*dir)
	if err := os.MkdirAll(targetDir, 0o755); err != nil {
		return err
	}

	team := spec.TeamSpec{
		Name:        *name,
		Description: "A starter AI team generated by agentteam init.",
		Models: spec.ModelConfig{
			DefaultModel: "openai/gpt-4.1-mini",
			Providers: map[string]spec.ProviderSpec{
				"openai": {
					Kind:      "openai-compatible",
					BaseURL:   "https://api.openai.com/v1",
					APIKeyEnv: "OPENAI_API_KEY",
				},
			},
		},
		Skills: []spec.SkillRequirement{
			{
				Name:    "github",
				Version: ">=0.1.0",
				Source: spec.SkillSource{
					Type: "registry",
				},
			},
		},
		Agents: []spec.AgentSpec{
			{Name: "captain", Role: "captain", Goal: "Own delivery and coordination.", Model: "openai/gpt-4.1", RequiredSkills: []string{"github"}},
			{Name: "planner", Role: "planner", Goal: "Break the task into clear work items.", Model: "openai/gpt-4.1-mini"},
			{Name: "researcher", Role: "researcher", Goal: "Collect facts and risks.", Model: "openai/gpt-4.1-mini"},
			{Name: "reviewer", Role: "reviewer", Goal: "Review the plan and final output.", Model: "openai/gpt-4.1-mini"},
		},
		Channels: []spec.ChannelConfig{
			{Kind: "cli", Enabled: true},
		},
		Policies: spec.PolicySpec{
			AllowExternalSkillInstall:   true,
			RequireApprovalForExtSkills: true,
			RequireApprovalForMessages:  true,
			RequireApprovalForGitWrite:  true,
		},
		Budget: spec.BudgetConfig{
			MaxDelegations: 8,
			MaxTokens:      120000,
		},
	}

	content, err := yaml.Marshal(team)
	if err != nil {
		return err
	}

	teamPath := filepath.Join(targetDir, "team.yaml")
	if err := os.WriteFile(teamPath, content, 0o644); err != nil {
		return err
	}

	fmt.Printf("Initialized %s\n", teamPath)
	return nil
}

func runTeam(args []string) error {
	fs := flag.NewFlagSet("run", flag.ContinueOnError)
	teamPath := fs.String("team", "team.yaml", "path to a team spec")
	task := fs.String("task", "", "task for the team")
	workDir := fs.String("workdir", ".", "runtime working directory")
	if err := fs.Parse(args); err != nil {
		return err
	}
	if strings.TrimSpace(*task) == "" {
		return fmt.Errorf("--task is required")
	}

	loaded, err := loadTeamWithEnv(*teamPath)
	if err != nil {
		return err
	}

	runner := runtime.NewRunner(filepath.Clean(*workDir))
	result, err := runner.Run(context.Background(), loaded, *task)
	if err != nil {
		return err
	}

	fmt.Printf("Run ID: %s\n", result.RunID)
	fmt.Println()
	fmt.Println(result.Summary)
	fmt.Println()
	fmt.Printf("Replay log: %s\n", result.ReplayPath)
	fmt.Printf("Checkpoint: %s\n", result.CheckpointPath)
	return nil
}

func runSkills(args []string) error {
	if len(args) == 0 {
		return fmt.Errorf("expected a skills subcommand")
	}

	switch args[0] {
	case "install":
		fs := flag.NewFlagSet("skills install", flag.ContinueOnError)
		name := fs.String("name", "", "skill name")
		sourceType := fs.String("source", "registry", "source type: local|registry|git")
		path := fs.String("path", "", "local skill path")
		url := fs.String("url", "", "git url")
		ref := fs.String("ref", "", "git ref")
		workDir := fs.String("workdir", ".", "runtime working directory")
		if err := fs.Parse(args[1:]); err != nil {
			return err
		}
		if strings.TrimSpace(*name) == "" {
			return fmt.Errorf("--name is required")
		}
		installer := skills.NewInstaller(filepath.Join(filepath.Clean(*workDir), ".agentteam", "skills"))
		result, err := installer.Install(spec.SkillRequirement{
			Name:    *name,
			Version: "latest",
			Source: spec.SkillSource{
				Type: *sourceType,
				Path: *path,
				URL:  *url,
				Ref:  *ref,
			},
		}, "")
		if err != nil {
			return err
		}
		fmt.Printf("Installed %s at %s\n", result.Name, result.InstallDir)
		return nil
	case "scaffold":
		fs := flag.NewFlagSet("skills scaffold", flag.ContinueOnError)
		name := fs.String("name", "", "skill name")
		dir := fs.String("dir", "", "target directory")
		description := fs.String("description", "", "skill description")
		if err := fs.Parse(args[1:]); err != nil {
			return err
		}
		if strings.TrimSpace(*name) == "" {
			return fmt.Errorf("--name is required")
		}
		targetDir := *dir
		if strings.TrimSpace(targetDir) == "" {
			targetDir = filepath.Join("skills", *name)
		}
		out, err := skills.Scaffold(*name, *description, targetDir)
		if err != nil {
			return err
		}
		fmt.Printf("Scaffolded %s at %s\n", *name, out)
		return nil
	case "search":
		fs := flag.NewFlagSet("skills search", flag.ContinueOnError)
		query := fs.String("query", "", "optional catalog search query")
		if err := fs.Parse(args[1:]); err != nil {
			return err
		}
		results := skills.Search(*query)
		if len(results) == 0 {
			fmt.Println("No matching skills found.")
			return nil
		}
		for _, result := range results {
			fmt.Printf("- %s [%s] %s\n", result.Name, result.Source, result.Description)
		}
		return nil
	case "list":
		fs := flag.NewFlagSet("skills list", flag.ContinueOnError)
		workDir := fs.String("workdir", ".", "runtime working directory")
		if err := fs.Parse(args[1:]); err != nil {
			return err
		}
		installer := skills.NewInstaller(filepath.Join(filepath.Clean(*workDir), ".agentteam", "skills"))
		installed, err := installer.ListInstalled()
		if err != nil {
			return err
		}
		if len(installed) == 0 {
			fmt.Println("No installed skills found.")
			return nil
		}
		for _, skill := range installed {
			fmt.Printf("- %s@%s %s (%s)\n", skill.Name, skill.Version, skill.Description, skill.Path)
		}
		return nil
	default:
		return fmt.Errorf("unknown skills subcommand %q", args[0])
	}
}

func runChannels(args []string) error {
	if len(args) == 0 {
		return fmt.Errorf("expected a channels subcommand")
	}

	switch args[0] {
	case "validate":
		fs := flag.NewFlagSet("channels validate", flag.ContinueOnError)
		teamPath := fs.String("team", "team.yaml", "path to a team spec")
		if err := fs.Parse(args[1:]); err != nil {
			return err
		}
		loaded, err := loadTeamWithEnv(*teamPath)
		if err != nil {
			return err
		}
		if err := channels.ValidateTeam(loaded); err != nil {
			return err
		}
		fmt.Println("Channel configuration looks good.")
		return nil
	default:
		return fmt.Errorf("unknown channels subcommand %q", args[0])
	}
}

func runModels(args []string) error {
	if len(args) == 0 {
		return fmt.Errorf("expected a models subcommand")
	}

	switch args[0] {
	case "explain":
		fs := flag.NewFlagSet("models explain", flag.ContinueOnError)
		teamPath := fs.String("team", "team.yaml", "path to a team spec")
		if err := fs.Parse(args[1:]); err != nil {
			return err
		}
		loaded, err := loadTeamWithEnv(*teamPath)
		if err != nil {
			return err
		}
		fmt.Println(loaded.ExplainModelSetup())
		return nil
	case "validate":
		fs := flag.NewFlagSet("models validate", flag.ContinueOnError)
		teamPath := fs.String("team", "team.yaml", "path to a team spec")
		if err := fs.Parse(args[1:]); err != nil {
			return err
		}
		loaded, err := loadTeamWithEnv(*teamPath)
		if err != nil {
			return err
		}
		if err := loaded.ValidateModelCredentials(); err != nil {
			return err
		}
		providers := loaded.ResolveProviders()
		sort.Slice(providers, func(i, j int) bool {
			return providers[i].Name < providers[j].Name
		})
		for _, provider := range providers {
			fmt.Printf("%s: kind=%s env=%s has_api_key=%t\n", provider.Name, provider.Kind, provider.APIKeyEnv, provider.HasAPIKey)
		}
		fmt.Println("Model credentials look good.")
		return nil
	default:
		return fmt.Errorf("unknown models subcommand %q", args[0])
	}
}

func runReplay(args []string) error {
	if len(args) == 0 {
		return fmt.Errorf("expected a replay subcommand")
	}

	switch args[0] {
	case "show":
		fs := flag.NewFlagSet("replay show", flag.ContinueOnError)
		runPath := fs.String("run", "", "path to a replay log")
		if err := fs.Parse(args[1:]); err != nil {
			return err
		}
		if strings.TrimSpace(*runPath) == "" {
			return fmt.Errorf("--run is required")
		}
		var result runtime.RunResult
		if err := observe.ReadJSON(*runPath, &result); err != nil {
			return err
		}
		fmt.Printf("Run ID: %s\n", result.RunID)
		fmt.Printf("Summary: %s\n", firstLine(result.Summary))
		fmt.Printf("Artifacts: %d\n", len(result.Artifacts))
		fmt.Printf("Work items: %d\n", len(result.WorkItems))
		fmt.Printf("Approvals: %d\n", len(result.Approvals))
		fmt.Println("Recent events:")
		start := 0
		if len(result.Events) > 5 {
			start = len(result.Events) - 5
		}
		for _, event := range result.Events[start:] {
			fmt.Printf("- %s %s: %s\n", event.Timestamp.Format(timeFormat), event.Actor, event.Message)
		}
		return nil
	default:
		return fmt.Errorf("unknown replay subcommand %q", args[0])
	}
}

func runInspect(args []string) error {
	if len(args) == 0 {
		return fmt.Errorf("expected an inspect subcommand")
	}

	switch args[0] {
	case "team":
		fs := flag.NewFlagSet("inspect team", flag.ContinueOnError)
		teamPath := fs.String("team", "team.yaml", "path to a team spec")
		format := fs.String("format", "text", "output format: text|mermaid")
		if err := fs.Parse(args[1:]); err != nil {
			return err
		}
		loaded, err := loadTeamWithEnv(*teamPath)
		if err != nil {
			return err
		}
		switch *format {
		case "text":
			fmt.Println(renderTeamInspect(loaded))
			return nil
		case "mermaid":
			fmt.Println(renderTeamMermaid(loaded))
			return nil
		default:
			return fmt.Errorf("unsupported inspect format %q", *format)
		}
	default:
		return fmt.Errorf("unknown inspect subcommand %q", args[0])
	}
}

const timeFormat = "2006-01-02 15:04:05Z07:00"

func firstLine(s string) string {
	lines := strings.Split(strings.TrimSpace(s), "\n")
	if len(lines) == 0 {
		return ""
	}
	return lines[0]
}

func loadTeamWithEnv(teamPath string) (*spec.TeamSpec, error) {
	cleanPath := filepath.Clean(teamPath)
	if err := loadDotEnvIfPresent(".env"); err != nil {
		return nil, err
	}
	if err := loadDotEnvIfPresent(filepath.Join(filepath.Dir(cleanPath), ".env")); err != nil {
		return nil, err
	}
	return spec.LoadTeam(cleanPath)
}

func loadDotEnvIfPresent(path string) error {
	content, err := os.ReadFile(path)
	if err != nil {
		if os.IsNotExist(err) {
			return nil
		}
		return err
	}

	scanner := bufio.NewScanner(strings.NewReader(string(content)))
	for scanner.Scan() {
		line := strings.TrimSpace(scanner.Text())
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		line = strings.TrimPrefix(line, "export ")
		key, value, ok := strings.Cut(line, "=")
		if !ok {
			continue
		}
		key = strings.TrimSpace(key)
		value = strings.Trim(strings.TrimSpace(value), `"'`)
		if key == "" || value == "" {
			continue
		}
		if _, exists := os.LookupEnv(key); exists {
			continue
		}
		if err := os.Setenv(key, value); err != nil {
			return err
		}
	}
	return scanner.Err()
}

func renderTeamInspect(team *spec.TeamSpec) string {
	lines := []string{
		fmt.Sprintf("Team: %s", team.Name),
		fmt.Sprintf("Description: %s", team.Description),
		fmt.Sprintf("Default model: %s", team.Models.DefaultModel),
	}

	providers := team.ResolveProviders()
	if len(providers) > 0 {
		sort.Slice(providers, func(i, j int) bool {
			return providers[i].Name < providers[j].Name
		})
		lines = append(lines, "", "Providers:")
		for _, provider := range providers {
			env := provider.APIKeyEnv
			if env == "" {
				env = "<inline-or-unset>"
			}
			lines = append(lines, fmt.Sprintf("- %s (%s) env=%s has_api_key=%t", provider.Name, provider.Kind, env, provider.HasAPIKey))
		}
	}

	lines = append(lines, "", "Agents:")
	for _, agent := range team.Agents {
		requiredSkills := "none"
		if len(agent.RequiredSkills) > 0 {
			requiredSkills = strings.Join(agent.RequiredSkills, ", ")
		}
		lines = append(lines, fmt.Sprintf("- %s [%s] model=%s skills=%s", agent.Name, agent.Role, team.ResolveModel(agent), requiredSkills))
	}

	requiredSkills := team.RequiredSkillRequirements()
	if len(requiredSkills) > 0 {
		sort.Slice(requiredSkills, func(i, j int) bool {
			return requiredSkills[i].Name < requiredSkills[j].Name
		})
		lines = append(lines, "", "Skills:")
		for _, skill := range requiredSkills {
			lines = append(lines, fmt.Sprintf("- %s source=%s version=%s", skill.Name, skill.Source.Type, skill.Version))
		}
	}

	if len(team.Channels) > 0 {
		lines = append(lines, "", "Channels:")
		for _, channel := range team.Channels {
			lines = append(lines, fmt.Sprintf("- %s enabled=%t", channel.Kind, channel.Enabled))
		}
	}

	lines = append(lines, "", "Policies:")
	lines = append(lines, fmt.Sprintf("- allow_external_skill_install=%t", team.Policies.AllowExternalSkillInstall))
	lines = append(lines, fmt.Sprintf("- require_approval_for_external_skills=%t", team.Policies.RequireApprovalForExtSkills))
	lines = append(lines, fmt.Sprintf("- require_approval_for_messages=%t", team.Policies.RequireApprovalForMessages))
	lines = append(lines, fmt.Sprintf("- require_approval_for_git_write=%t", team.Policies.RequireApprovalForGitWrite))
	lines = append(lines, "", fmt.Sprintf("Delegation graph: agentteam inspect team --team %s --format mermaid", team.SourcePath))

	return strings.Join(lines, "\n")
}

func renderTeamMermaid(team *spec.TeamSpec) string {
	captain := captainName(team)
	lines := []string{
		"flowchart TD",
		fmt.Sprintf(`    task["Task"] --> captain["%s"]`, captain),
	}
	for _, agent := range team.Agents {
		if agent.Role == "captain" {
			continue
		}
		lines = append(lines, fmt.Sprintf(`    captain --> %s["%s (%s)"]`, mermaidNodeID(agent.Name), agent.Name, team.ResolveModel(agent)))
	}
	return strings.Join(lines, "\n")
}

func captainName(team *spec.TeamSpec) string {
	for _, agent := range team.Agents {
		if agent.Role == "captain" {
			return agent.Name
		}
	}
	return "captain"
}

func mermaidNodeID(name string) string {
	replacer := strings.NewReplacer("-", "_", " ", "_", "/", "_", ".", "_")
	return "node_" + replacer.Replace(name)
}

func exitErr(err error) {
	fmt.Fprintln(os.Stderr, "error:", err)
	os.Exit(1)
}
