package main

import (
	"context"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"gopkg.in/yaml.v3"

	"github.com/daewoochen/agent-team-go/pkg/channels"
	"github.com/daewoochen/agent-team-go/pkg/observe"
	"github.com/daewoochen/agent-team-go/pkg/runtime"
	"github.com/daewoochen/agent-team-go/pkg/skills"
	"github.com/daewoochen/agent-team-go/pkg/spec"
)

func main() {
	if len(os.Args) < 2 {
		usage()
		os.Exit(1)
	}

	switch os.Args[1] {
	case "init":
		if err := runInit(os.Args[2:]); err != nil {
			exitErr(err)
		}
	case "run":
		if err := runTeam(os.Args[2:]); err != nil {
			exitErr(err)
		}
	case "skills":
		if err := runSkills(os.Args[2:]); err != nil {
			exitErr(err)
		}
	case "channels":
		if err := runChannels(os.Args[2:]); err != nil {
			exitErr(err)
		}
	case "models":
		if err := runModels(os.Args[2:]); err != nil {
			exitErr(err)
		}
	case "replay":
		if err := runReplay(os.Args[2:]); err != nil {
			exitErr(err)
		}
	case "version":
		fmt.Println("agentteam v0.1.0")
	default:
		usage()
		os.Exit(1)
	}
}

func usage() {
	fmt.Fprintln(os.Stderr, `agentteam builds and runs multi-agent teams in Go.

Usage:
  agentteam init --name demo --dir ./demo
  agentteam run --team ./team.yaml --task "Ship the v0.1 release"
  agentteam skills install --name github --source local --path ./skills/github
  agentteam channels validate --team ./team.yaml
  agentteam models explain --team ./team.yaml
  agentteam models validate --team ./team.yaml
  agentteam replay show --run ./.agentteam/runs/<run>.json
  agentteam version`)
}

func runInit(args []string) error {
	fs := flag.NewFlagSet("init", flag.ContinueOnError)
	name := fs.String("name", "demo-team", "team name")
	dir := fs.String("dir", ".", "target directory")
	if err := fs.Parse(args); err != nil {
		return err
	}

	targetDir := filepath.Clean(*dir)
	if err := os.MkdirAll(targetDir, 0o755); err != nil {
		return err
	}

	team := spec.TeamSpec{
		Name:        *name,
		Description: "A starter AI team generated by agentteam init.",
		Models: spec.ModelConfig{
			DefaultModel: "openai/gpt-4.1-mini",
			Providers: map[string]spec.ProviderSpec{
				"openai": {
					Kind:      "openai-compatible",
					BaseURL:   "https://api.openai.com/v1",
					APIKeyEnv: "OPENAI_API_KEY",
				},
			},
		},
		Skills: []spec.SkillRequirement{
			{
				Name:    "github",
				Version: ">=0.1.0",
				Source: spec.SkillSource{
					Type: "registry",
				},
			},
		},
		Agents: []spec.AgentSpec{
			{Name: "captain", Role: "captain", Goal: "Own delivery and coordination.", Model: "openai/gpt-4.1", RequiredSkills: []string{"github"}},
			{Name: "planner", Role: "planner", Goal: "Break the task into clear work items.", Model: "openai/gpt-4.1-mini"},
			{Name: "researcher", Role: "researcher", Goal: "Collect facts and risks.", Model: "openai/gpt-4.1-mini"},
			{Name: "reviewer", Role: "reviewer", Goal: "Review the plan and final output.", Model: "openai/gpt-4.1-mini"},
		},
		Channels: []spec.ChannelConfig{
			{Kind: "cli", Enabled: true},
		},
		Policies: spec.PolicySpec{
			AllowExternalSkillInstall:   true,
			RequireApprovalForExtSkills: true,
			RequireApprovalForMessages:  true,
			RequireApprovalForGitWrite:  true,
		},
		Budget: spec.BudgetConfig{
			MaxDelegations: 8,
			MaxTokens:      120000,
		},
	}

	content, err := yaml.Marshal(team)
	if err != nil {
		return err
	}

	teamPath := filepath.Join(targetDir, "team.yaml")
	if err := os.WriteFile(teamPath, content, 0o644); err != nil {
		return err
	}

	fmt.Printf("Initialized %s\n", teamPath)
	return nil
}

func runTeam(args []string) error {
	fs := flag.NewFlagSet("run", flag.ContinueOnError)
	teamPath := fs.String("team", "team.yaml", "path to a team spec")
	task := fs.String("task", "", "task for the team")
	workDir := fs.String("workdir", ".", "runtime working directory")
	if err := fs.Parse(args); err != nil {
		return err
	}
	if strings.TrimSpace(*task) == "" {
		return fmt.Errorf("--task is required")
	}

	loaded, err := spec.LoadTeam(*teamPath)
	if err != nil {
		return err
	}

	runner := runtime.NewRunner(filepath.Clean(*workDir))
	result, err := runner.Run(context.Background(), loaded, *task)
	if err != nil {
		return err
	}

	fmt.Printf("Run ID: %s\n", result.RunID)
	fmt.Println()
	fmt.Println(result.Summary)
	fmt.Println()
	fmt.Printf("Replay log: %s\n", result.ReplayPath)
	fmt.Printf("Checkpoint: %s\n", result.CheckpointPath)
	return nil
}

func runSkills(args []string) error {
	if len(args) == 0 {
		return fmt.Errorf("expected a skills subcommand")
	}

	switch args[0] {
	case "install":
		fs := flag.NewFlagSet("skills install", flag.ContinueOnError)
		name := fs.String("name", "", "skill name")
		sourceType := fs.String("source", "registry", "source type: local|registry|git")
		path := fs.String("path", "", "local skill path")
		url := fs.String("url", "", "git url")
		ref := fs.String("ref", "", "git ref")
		workDir := fs.String("workdir", ".", "runtime working directory")
		if err := fs.Parse(args[1:]); err != nil {
			return err
		}
		if strings.TrimSpace(*name) == "" {
			return fmt.Errorf("--name is required")
		}
		installer := skills.NewInstaller(filepath.Join(filepath.Clean(*workDir), ".agentteam", "skills"))
		result, err := installer.Install(spec.SkillRequirement{
			Name:    *name,
			Version: "latest",
			Source: spec.SkillSource{
				Type: *sourceType,
				Path: *path,
				URL:  *url,
				Ref:  *ref,
			},
		}, "")
		if err != nil {
			return err
		}
		fmt.Printf("Installed %s at %s\n", result.Name, result.InstallDir)
		return nil
	default:
		return fmt.Errorf("unknown skills subcommand %q", args[0])
	}
}

func runChannels(args []string) error {
	if len(args) == 0 {
		return fmt.Errorf("expected a channels subcommand")
	}

	switch args[0] {
	case "validate":
		fs := flag.NewFlagSet("channels validate", flag.ContinueOnError)
		teamPath := fs.String("team", "team.yaml", "path to a team spec")
		if err := fs.Parse(args[1:]); err != nil {
			return err
		}
		loaded, err := spec.LoadTeam(*teamPath)
		if err != nil {
			return err
		}
		if err := channels.ValidateTeam(loaded); err != nil {
			return err
		}
		fmt.Println("Channel configuration looks good.")
		return nil
	default:
		return fmt.Errorf("unknown channels subcommand %q", args[0])
	}
}

func runModels(args []string) error {
	if len(args) == 0 {
		return fmt.Errorf("expected a models subcommand")
	}

	switch args[0] {
	case "explain":
		fs := flag.NewFlagSet("models explain", flag.ContinueOnError)
		teamPath := fs.String("team", "team.yaml", "path to a team spec")
		if err := fs.Parse(args[1:]); err != nil {
			return err
		}
		loaded, err := spec.LoadTeam(*teamPath)
		if err != nil {
			return err
		}
		fmt.Println(loaded.ExplainModelSetup())
		return nil
	case "validate":
		fs := flag.NewFlagSet("models validate", flag.ContinueOnError)
		teamPath := fs.String("team", "team.yaml", "path to a team spec")
		if err := fs.Parse(args[1:]); err != nil {
			return err
		}
		loaded, err := spec.LoadTeam(*teamPath)
		if err != nil {
			return err
		}
		if err := loaded.ValidateModelCredentials(); err != nil {
			return err
		}
		providers := loaded.ResolveProviders()
		sort.Slice(providers, func(i, j int) bool {
			return providers[i].Name < providers[j].Name
		})
		for _, provider := range providers {
			fmt.Printf("%s: kind=%s env=%s has_api_key=%t\n", provider.Name, provider.Kind, provider.APIKeyEnv, provider.HasAPIKey)
		}
		fmt.Println("Model credentials look good.")
		return nil
	default:
		return fmt.Errorf("unknown models subcommand %q", args[0])
	}
}

func runReplay(args []string) error {
	if len(args) == 0 {
		return fmt.Errorf("expected a replay subcommand")
	}

	switch args[0] {
	case "show":
		fs := flag.NewFlagSet("replay show", flag.ContinueOnError)
		runPath := fs.String("run", "", "path to a replay log")
		if err := fs.Parse(args[1:]); err != nil {
			return err
		}
		if strings.TrimSpace(*runPath) == "" {
			return fmt.Errorf("--run is required")
		}
		var result runtime.RunResult
		if err := observe.ReadJSON(*runPath, &result); err != nil {
			return err
		}
		fmt.Printf("Run ID: %s\n", result.RunID)
		fmt.Printf("Summary: %s\n", firstLine(result.Summary))
		fmt.Printf("Artifacts: %d\n", len(result.Artifacts))
		fmt.Printf("Work items: %d\n", len(result.WorkItems))
		fmt.Printf("Approvals: %d\n", len(result.Approvals))
		fmt.Println("Recent events:")
		start := 0
		if len(result.Events) > 5 {
			start = len(result.Events) - 5
		}
		for _, event := range result.Events[start:] {
			fmt.Printf("- %s %s: %s\n", event.Timestamp.Format(timeFormat), event.Actor, event.Message)
		}
		return nil
	default:
		return fmt.Errorf("unknown replay subcommand %q", args[0])
	}
}

const timeFormat = "2006-01-02 15:04:05Z07:00"

func firstLine(s string) string {
	lines := strings.Split(strings.TrimSpace(s), "\n")
	if len(lines) == 0 {
		return ""
	}
	return lines[0]
}

func exitErr(err error) {
	fmt.Fprintln(os.Stderr, "error:", err)
	os.Exit(1)
}
