package skills

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"gopkg.in/yaml.v3"
)

func Scaffold(name, description, targetDir string) (string, error) {
	name = strings.TrimSpace(name)
	if name == "" {
		return "", fmt.Errorf("skill name is required")
	}

	targetDir = filepath.Clean(targetDir)
	if targetDir == "." || targetDir == "" {
		targetDir = filepath.Join("skills", name)
	}
	if strings.TrimSpace(description) == "" {
		description = "Custom skill scaffold generated by agentteam."
	}

	if err := os.MkdirAll(targetDir, 0o755); err != nil {
		return "", err
	}
	if _, err := os.Stat(filepath.Join(targetDir, manifestFile)); err == nil {
		return "", fmt.Errorf("skill scaffold already exists at %s", targetDir)
	}

	manifest := Manifest{
		Name:        name,
		Version:     "0.1.0",
		Description: description,
		Permissions: []string{"read:workspace"},
		Entrypoints: []string{"prompt.md"},
		Source: SourceInfo{
			Type: "local",
		},
	}
	content, err := yaml.Marshal(manifest)
	if err != nil {
		return "", err
	}
	if err := os.WriteFile(filepath.Join(targetDir, manifestFile), content, 0o644); err != nil {
		return "", err
	}

	prompt := strings.Join([]string{
		fmt.Sprintf("# %s", name),
		"",
		"## Purpose",
		description,
		"",
		"## Instructions",
		"- Describe when the skill should be used.",
		"- Explain the inputs the agent should expect.",
		"- Define the output format the rest of the team can rely on.",
	}, "\n")
	if err := os.WriteFile(filepath.Join(targetDir, "prompt.md"), []byte(prompt), 0o644); err != nil {
		return "", err
	}

	return targetDir, nil
}
